# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates a collection of open source static analysis tools
# with GitHub code scanning. For documentation, or to provide feedback, visit
# https://github.com/github/ossar-action
name: OSSAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '35 9 * * 0'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  OSSAR-Scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@latest # latest
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@latest # latest

      # Run open source static analysis tools
      - name: Run OSSAR
        uses: github/ossar-action@latest # latest
        id: ossar

      # Upload results to the Security tab
      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@latest # latest
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
