name: "publish to npm"
on: workflow_dispatch
permissions:
  contents: read

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: ⬇️ Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
              with:
                  token: ${{ secrets.ACCESS_TOKEN }}
                  ref: ${{github.event.pull_request.head.sha}}
                  fetch-depth: 0

            - name: 🤝 Set Node version from .nvmrc
              run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

            - name: ⎔ Setup node
              # sets up the .npmrc file to publish to npm
              uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
              with:
                  node-version: ${{ env.NVMRC }}
                  registry-url: "https://registry.npmjs.org"

            - name: 📥 Download deps
              uses: bahmutov/npm-install@237ded403e6012a48281f4572eab0c8eafe55b3f # v1.10.1
              with:
                  useLockFile: false

            - name: Configure git user
              run: |
                  git config --global user.email ${{ github.actor }}@users.noreply.github.com
                  git config --global user.name ${{ github.actor }}

            - name: ▶️ Run release
              run: npm run release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
