name: validate
on:
    # run on push but only for the main branch
    push:
        branches:
            - main
    # run for every pull request
    pull_request: {}
permissions:
  contents: read

jobs:
    main:
        permissions:
          contents: read  # for actions/checkout to fetch code
          pull-requests: read  # for wagoid/commitlint-github-action to get commits in PR
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: ⬇️ Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
              with:
                  ref: ${{github.event.pull_request.head.sha}}
                  fetch-depth: 0

            - name: 🤝 Set Node version from .nvmrc
              run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

            - name: ⎔ Setup node
              uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
              with:
                  node-version: ${{ env.NVMRC }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@237ded403e6012a48281f4572eab0c8eafe55b3f # v1.10.1
              with:
                  useLockFile: false

            - name: ▶️ Run validate script
              run: npm run validate

            - name: 👕 Lint commit messages
              uses: wagoid/commitlint-github-action@416045160973f9fff174ac6698412cfe7181c3f3 # v4.1.15

            - name: ⬆️ Upload coverage report
              uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2.1.0
